force-app/main/default/objects/Country__c/fields/ExternalID__c.field-meta.xml
<CustomField>
    <fullName>ExternalID__c</fullName>
    <description>Sportmonks ID</description>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Player__c/Player__c.object-meta.xml
<CustomObject>
    <label>Player</label>
    <nameField>
        <displayFormat>PL-{000000}</displayFormat>
        <label>Player ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Player__c/fields/BattingStyle__c.field-meta.xml
<CustomField>
    <fullName>BattingStyle__c</fullName>
    <label>Batting Style</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>right-hand-bat</fullName>
                <label>Right Hand Batter</label>
            </value>
            <value>
                <fullName>left-hand-bat</fullName>
                <label>Left Hand Batter</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Player__c/fields/BowlingStyle__c.field-meta.xml
<CustomField>
    <fullName>BowlingStyle__c</fullName>
    <label>Bowling Style</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>legbreak</fullName>
                <label>Leg-spin</label>
            </value>
            <value>
                <fullName>offbreak</fullName>
                <label>Off-Spin</label>
            </value>
            <value>
                <fullName>reverse</fullName>
                <label>Reverse</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Player__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Players</relationshipLabel>
    <relationshipName>Players</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Player__c/fields/DateOfBirth__c.field-meta.xml
<CustomField>
    <fullName>DateOfBirth__c</fullName>
    <label>DateOfBirth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Player__c/fields/ExternalID__c.field-meta.xml
<CustomField>
    <fullName>ExternalID__c</fullName>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Player__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Player__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>m</fullName>
                <label>Male</label>
            </value>
            <value>
                <fullName>f</fullName>
                <label>Female</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Player__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Player__c/fields/Photo__c.field-meta.xml
<CustomField>
    <fullName>Photo__c</fullName>
    <label>Photo</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/SMSyncPlayers.cls
public without sharing class SMSyncPlayers implements Queueable, Database.AllowsCallouts {
    
    Database.Cursor locator;
    private Integer position;

    private final Integer BATCH_SIZE = 1;
    private static Map<String, String> countryIdMap = new Map<String, String>();

    public SMSyncPlayers() {
        position = 0;
        locator = Database.getCursor('SELECT Id, Name, ExternalID__c FROM Country__c WHERE ExternalID__c != NULL');
    }

    public void execute(QueueableContext qc) {

        for (Country__c ctr : (List<Country__c>) locator.fetch(position, BATCH_SIZE)) {
            position++;
            countryIdMap.put(ctr.ExternalID__c, ctr.Id);
        }
        
        String countryExternalIds = String.join(countryIdMap.keySet(), ',').removeEnd(',');
        fetchPlayerRecords(countryExternalIds);
        enqueueThis();
    }

    private void fetchPlayerRecords(String countryExternalIds) {
        
        Http http = new Http();
        HttpRequest req = new HttpRequest();

        String token = SportMonksApi__c.getOrgDefaults().Token__c;
        String calloutURL = 'Callout:SportMonks/players?api_token=' + token + '&filter[country_id]=' + countryExternalIds;

        req.setEndpoint(calloutURL);
        req.setMethod('GET');

        HttpResponse res = http.send(req);

        if (res.getStatusCode() == 200) {
            try {
                PlayerResponse response = (PlayerResponse) JSON.deserialize(res.getBody(), PlayerResponse.Class);
                upsertPlayers(response);
            } catch (Exception e) {
                System.debug('Error:' + e.getMessage());
            }
        }
    }

    private void upsertPlayers(PlayerResponse response) {
        
        List<Player__c> playerToUpsert = new List<Player__c>();

        for (Player ply : response.data) {
            Player__c plySObject = new Player__c();
            plySObject.Country__c = countryIdMap.get(String.valueOf(ply.country_id));
            plySObject.ExternalID__c = String.valueOf(ply.id);
            plySObject.FirstName__c = ply.firstname;
            plySObject.LastName__c = ply.lastname;
            plySObject.Gender__c = ply.gender;
            plySObject.Photo__c = ply.image_path;
            plySObject.BattingStyle__c = ply.battingstyle;
            plySObject.BowlingStyle__c = ply.bowlingstyle;

            if (ply.dateofbirth != '0000-00-00') {
                List<String> dateValues = ply.dateofbirth.split('-');
                plySObject.DateOfBirth__c = Date.newInstance(Integer.valueOf(dateValues[0]), Integer.valueOf(dateValues[1]), Integer.valueOf(dateValues[2]));
            }

            playerToUpsert.add(plySObject);
        }

        if (!playerToUpsert.isEmpty()) {
            Database.UpsertResult [] result = Database.upsert(playerToUpsert, Player__c.ExternalID__c, false);
            for (Database.UpsertResult res : result) {
                System.debug(res.getErrors());
            }
        }
    }

    private void enqueueThis() {
        if (position < locator.getNumRecords()) {
            System.enqueueJob(this);
        }
    }

    public class PlayerResponse {
        public List<Player> data;
    }

    public class Player {
        public String resoure;
        public Integer id;
        public Integer country_id;
        public String firstname;
        public String lastname;
        public String image_path;
        public String dateofbirth;
        public String gender;
        public String battingstyle;
        public String bowlingstyle;
        public Position positionInfo;
    }

    public class Position {
        public String name;
    }

}