force-app/main/default/objects/Country__c/fields/ISOCode__c.field-meta.xml
<CustomField>
    <fullName>ISOCode__c</fullName>
    <label>ISO Code</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/Prefix__c.field-meta.xml
<CustomField>
    <fullName>Prefix__c</fullName>
    <label>Prefix</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/VerifyPhoneCtrl.cls
public with sharing class VerifyPhoneCtrl {

    public static final String VERIFY_PHONE_NUMBER_FLOW = 'Verify_Phone_Number_ALF';

    @AuraEnabled(cacheable=true)
    public static VerifyPhoneOutputApexDefined verifyNumber(String country, String phoneNumber) {
        try {

            Map<String, Object> flowInputVars = new Map<String, Object>{ 'defaultCountry' => country, 'phoneNumber' => phoneNumber };
            Flow.Interview verifyPhoneNumberFlow = Flow.Interview.createInterview(VERIFY_PHONE_NUMBER_FLOW, flowInputVars);

            verifyPhoneNumberFlow.start();
            VerifyPhoneOutputApexDefined response = (VerifyPhoneOutputApexDefined) verifyPhoneNumberFlow.getVariableValue('CalloutResponse');

            if (response != null && response.error.status == 'error') {
                new AuraHandledException(response.error.message);
            } else {
                new AuraHandledException('Something went wrong.');
            }

            return response;

        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled(cacheable=true)
    public static List<Country__c> getCountryCodes() {
        try {
            return [SELECT Id, Name, ISOCode__c, Prefix__c FROM Country__c];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}